# Generated by Django 4.2.14 on 2024-08-03 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "exercise_after_meal",
                    models.BooleanField(default=False, verbose_name="식후 1시간 내 운동했나요?"),
                ),
                (
                    "breakfast",
                    models.BooleanField(default=False, verbose_name="아침식사 했나요?"),
                ),
                (
                    "sleep",
                    models.BooleanField(default=False, verbose_name="7시간 이상 충분히 잤나요?"),
                ),
                (
                    "dietary_fiber",
                    models.BooleanField(default=False, verbose_name="충분한 식이섬유를 섭취했나요?"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "체크리스트",
                "verbose_name_plural": "체크리스트들",
                "unique_together": {("user", "date")},
            },
        ),
    ]
