# Generated by Django 4.2.3 on 2024-08-03 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkList", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklist",
            name="breakfast",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="dietary_fiber",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="exercise_after_meal",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="sleep",
        ),
        migrations.AddField(
            model_name="checklist",
            name="exercise",
            field=models.BooleanField(default=False, verbose_name="운동 여부"),
        ),
        migrations.AddField(
            model_name="checklist",
            name="meal_order",
            field=models.BooleanField(default=False, verbose_name="식사 순서"),
        ),
        migrations.AddField(
            model_name="checklist",
            name="sugar",
            field=models.BooleanField(default=False, verbose_name="식후 액상과당 섭취"),
        ),
        migrations.AddField(
            model_name="checklist",
            name="when",
            field=models.PositiveSmallIntegerField(
                default=False,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
    ]
