# Generated by Django 4.2.14 on 2024-08-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="isDoctor",
            field=models.BooleanField(default=False),
        ),
    ]
